### ISSUE TITLE
How to save entire data output in tab-delimited file and png file format for clonosGP

### ISSUE THREAD

**Issue by Sunilpachakar** [dvav/clonosGP#2]
Hello,

I have run clonosGP successfully and want to save results in tab-delimited file and png file format.

I have three following questions.

1) After running the last command `RES['data']` it gives a data matrix with some columns and rows. On-screen it prints only a few rows, like 10 rows.
I want to store this information in tab-delimited format. I use the following command to do it 

`abc=RES['data'].values`

`for i in range(0,185):
    for j in range(0,20):
        print(abc[i][j],end='\t')
    print()`

My data contains 185 mutations(actually 37 mutations for 5 longitudinally samples) and 20 rows. hence I put the number of rows and mutations in above for loop and print it on the screen, which gives me all rows(185 rows) and columns.

**Is there any command to save all data from `RES['data']` command into a tab-delimited file format** 

2) After running the command `cln.viz.plot_summary(RES, figsize=(10, 15));` want to save results in png or pdf format. I have saved it now by right click and save as an image but the annotation on the X and Y axis is not visible. 
I have also taken a screenshot of the image but I feel that it reduces the quality of the graphs. However, opening the downloaded image in paint works for me. 

**I request you to suggest to me the command to save the output results in image format.**

3) **What is the difference between CCF (cancer cell fraction) and CCF_ (rough estimate of CCF).**

**Comment by dvav** [comment]
Hi @Sunilpachakar,

Thank you for your interest in clonosGP.

> **Is there any command to save all data from `RES['data']` command into a tab-delimited file format**

`RES['data']` is a Pandas data frame, so you could use something like this: `RES[‘data’].to_csv('output.tsv',sep='\t',index=False)`

> **I request you to suggest to me the command to save the output results in image format.**

Try this immediately after `plot_sumary` (in the same cell):

```
import matplotlib.pyplot as plt
plt.savefig('foo.ext', bbox_inches='tight')
```

> **What is the difference between CCF (cancer cell fraction) and CCF_ (rough estimate of CCF).**

CCF_ is a first, rough estimate of the cancer cell fraction. CCF is the final estimate of the cancer cell fraction derived from a complicated statistical process, which includes clustering (see paper for details). You can ignore CCF_.

Please, let me know if the above works for you.
